apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: testStarter-api
  description: mySpringBootStartTest
spec:
  type: openapi
  lifecycle: experimental
  owner: yumc/g-arch
  system: TestSpringBootStarter
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Test API
      license:
        name: MIT
    servers:
      - url: http://test.starter.usecase.yumc.local/v1
    paths:
      /get/info:
        get:
          summary: List all artists
